Bottle v0.13.4 server starting up (using WSGIRefServer())...
Listening on http://localhost:4444/
Hit Ctrl-C to quit.

Traceback (most recent call last):
  File "/home/pinf/scripts/Server.py", line 183, in <module>
    run(host='localhost', port=4444, debug=True)
  File "/usr/local/lib/python3.10/dist-packages/bottle.py", line 3985, in run
    server.run(app)
  File "/usr/local/lib/python3.10/dist-packages/bottle.py", line 3528, in run
    self.srv = make_server(self.host, self.port, app, server_cls,
  File "/usr/lib/python3.10/wsgiref/simple_server.py", line 154, in make_server
    server = server_class((host, port), handler_class)
  File "/usr/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.10/wsgiref/simple_server.py", line 50, in server_bind
    HTTPServer.server_bind(self)
  File "/usr/lib/python3.10/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Bottle v0.13.4 server starting up (using WSGIRefServer())...
Listening on http://localhost:4444/
Hit Ctrl-C to quit.

127.0.0.1 - - [17/Oct/2025 17:44:42] "GET / HTTP/1.1" 404 726
127.0.0.1 - - [17/Oct/2025 17:46:02] "GET /personal HTTP/1.1" 200 472
127.0.0.1 - - [17/Oct/2025 17:50:03] "GET /personal HTTP/1.1" 200 472
Bottle v0.13.4 server starting up (using WSGIRefServer())...
Listening on http://0.0.0.0:4444/
Hit Ctrl-C to quit.

192.168.77.14 - - [19/Oct/2025 21:31:32] "GET /personal HTTP/1.1" 200 472
192.168.77.14 - - [19/Oct/2025 21:31:32] "GET /favicon.ico HTTP/1.1" 404 751
----------------------------------------
Exception occurred during processing of request from ('66.132.153.113', 38260)
Traceback (most recent call last):
  File "/usr/lib/python3.10/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.10/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.10/wsgiref/simple_server.py", line 118, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
66.132.153.113 - - [19/Oct/2025 23:56:25] code 400, message Bad HTTP/0.9 request type ('\\x16\\x03\\x01\\x00î\\x01\\x00\\x00ê\\x03\\x03\\x84\\x91\\x16')
66.132.153.113 - - [19/Oct/2025 23:56:25] "\x16\x03\x01\x00î\x01\x00\x00ê\x03\x03\x84\x91\x16 EÊ¸h¥o¹" 400 -
66.132.153.113 - - [19/Oct/2025 23:56:28] "GET / HTTP/1.1" 404 730
66.132.153.113 - - [19/Oct/2025 23:56:36] "GET / HTTP/1.1" 404 730
66.132.153.113 - - [19/Oct/2025 23:56:37] code 505, message Invalid HTTP version (2.0)
66.132.153.113 - - [19/Oct/2025 23:56:37] "PRI * HTTP/2.0" 505 -
66.132.153.113 - - [19/Oct/2025 23:56:45] code 505, message Invalid HTTP version (2.0)
66.132.153.113 - - [19/Oct/2025 23:56:45] "PRI * HTTP/2.0" 505 -
66.132.153.113 - - [19/Oct/2025 23:56:45] "GET /sitemap.xml HTTP/1.1" 404 752
3.134.148.59 - - [20/Oct/2025 02:09:37] "GET / HTTP/1.1" 404 730
3.134.148.59 - - [20/Oct/2025 02:11:33] "GET / HTTP/1.1" 404 730
3.134.148.59 - - [20/Oct/2025 02:12:46] code 400, message Bad HTTP/0.9 request type ('\\x16\\x03\\x01\\x00{\\x01\\x00\\x00w\\x03\\x03:!\\\\L}yðM\\x9aV¶\\x81>uá×\\x19¸Ã|ñ%D`8\\x84²\\x94/ìò\\x92\\x00\\x00\\x1aÀ/À+À\\x11À\\x07À\\x13À')
3.134.148.59 - - [20/Oct/2025 02:12:46] "\x16\x03\x01\x00{\x01\x00\x00w\x03\x03:!\\L}yðM\x9aV¶\x81>uá×\x19¸Ã|ñ%D`8\x84²\x94/ìò\x92\x00\x00\x1aÀ/À+À\x11À\x07À\x13À\x09À\x14À" 400 -
3.134.148.59 - - [20/Oct/2025 02:14:40] code 400, message Bad request syntax ('SSH-2.0-Go')
3.134.148.59 - - [20/Oct/2025 02:14:40] "SSH-2.0-Go" 400 -
3.134.148.59 - - [20/Oct/2025 02:15:47] code 400, message Bad HTTP/0.9 request type ('\\x16\\x03\\x01\\x00{\\x01\\x00\\x00w\\x03\\x03²\\x13Åd\\x9bEj\\x08\\x8cÆ¤6\\x12]A0D#é¯ûìôFà0M¶Q°¶\\x02\\x00\\x00\\x1aÀ/À+À\\x11À\\x07À\\x13À')
3.134.148.59 - - [20/Oct/2025 02:15:47] "\x16\x03\x01\x00{\x01\x00\x00w\x03\x03²\x13Åd\x9bEj\x08\x8cÆ¤6\x12]A0D#é¯ûìôFà0M¶Q°¶\x02\x00\x00\x1aÀ/À+À\x11À\x07À\x13À\x09À\x14À" 400 -
165.22.60.26 - - [20/Oct/2025 07:30:59] "GET /aaa9 HTTP/1.1" 404 738
165.22.60.26 - - [20/Oct/2025 07:30:59] "GET /aab8 HTTP/1.1" 404 738
165.22.60.26 - - [20/Oct/2025 07:31:00] "GET / HTTP/1.1" 404 730
150.214.75.182 - - [20/Oct/2025 08:32:04] "GET /personal HTTP/1.1" 200 472
150.214.75.182 - - [20/Oct/2025 08:32:04] "GET /favicon.ico HTTP/1.1" 404 752
150.214.75.182 - - [20/Oct/2025 08:32:39] "GET / HTTP/1.1" 404 730
150.214.75.182 - - [20/Oct/2025 08:32:39] "GET /favicon.ico HTTP/1.1" 404 752
150.214.75.182 - - [20/Oct/2025 08:32:55] "GET /personal HTTP/1.1" 200 472
150.214.75.182 - - [20/Oct/2025 08:33:00] code 400, message Bad request version ('\\x9aR¯+\\x88Õ')
150.214.75.182 - - [20/Oct/2025 08:33:00] "\x16\x03\x01\x07O\x01\x00\x07K\x03\x03Ù?hj\x1fÅ\x1f\x9aR¯+\x88Õ" 400 -
150.214.231.66 - - [20/Oct/2025 08:33:00] code 400, message Bad request syntax ('\\x16\\x03\\x01\\x01\\x04\\x01\\x00\\x01\\x00\\x03\\x03Ð´\\x8b¿¥óT\\x92ÿ2ëmPx\\x0f¿°§lØ\\x01Õ\\x13B\\x9fi\\x18N§fc3 ')
150.214.231.66 - - [20/Oct/2025 08:33:00] "\x16\x03\x01\x01\x04\x01\x00\x01\x00\x03\x03Ð´\x8b¿¥óT\x92ÿ2ëmPx\x0f¿°§lØ\x01Õ\x13B\x9fi\x18N§fc3 " 400 -
150.214.75.182 - - [20/Oct/2025 08:33:00] code 400, message Bad request version ('\\x9dc')
150.214.75.182 - - [20/Oct/2025 08:33:00] "\x16\x03\x01\x02~\x01\x00\x02z\x03\x03CÆ§Ëv#\x1cÑG7jôlgw\x015¡\x92\x86_á\x835^@mó\x06 \x15\x8b \x9dc" 400 -
